version: '3'
services:
  nginx:
    container_name: some-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8083"
